# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SES', '0002_auto_20171007_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Authorization_Code',
            field=models.CharField(max_length=30, verbose_name='Auto Generated Auth Code'),
        ),
    ]
