# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SES', '0003_auto_20171007_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterStatus',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=50, verbose_name='Status of Register')),
            ],
            options={
                'ordering': ('Id',),
            },
        ),
        migrations.AddField(
            model_name='register',
            name='Status_Id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='SES.RegisterStatus'),
        ),
    ]
