# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SES', '0004_auto_20171007_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Subject', models.CharField(max_length=60, verbose_name='Subject of Email')),
                ('Body', models.CharField(max_length=1000, verbose_name='Body of Email')),
                ('From', models.CharField(max_length=50, verbose_name='From Username')),
            ],
            options={
                'ordering': ('Id',),
            },
        ),
        migrations.CreateModel(
            name='NotificationStatus',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=50, verbose_name='Status of Notification')),
            ],
            options={
                'ordering': ('Id',),
            },
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=50, verbose_name='Type of Notification')),
            ],
            options={
                'ordering': ('Id',),
            },
        ),
    ]
