# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SES', '0005_emailtemplate_notificationstatus_notificationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('From_Id', models.IntegerField(default=0)),
                ('To_Id', models.IntegerField(default=0)),
                ('Message_Id', models.IntegerField(default=0)),
                ('Status_Id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='SES.NotificationStatus')),
                ('Type_Id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='SES.NotificationType')),
            ],
            options={
                'ordering': ('Id',),
            },
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='Filename',
            field=models.FileField(blank=True, null=True, upload_to='static/templates/email', verbose_name='Filename'),
        ),
    ]
