# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SES', '0009_auto_20171008_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(default='noemail@noemail.com', max_length=100, verbose_name='Email of Register')),
                ('Inserted', models.DateTimeField(auto_now_add=True, verbose_name='Time inserted')),
            ],
            options={
                'ordering': ('Id',),
            },
        ),
        migrations.CreateModel(
            name='EmailAddressStatus',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=50, verbose_name='Status of Email Address')),
            ],
            options={
                'ordering': ('Id',),
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Inserted', models.DateTimeField(auto_now_add=True, verbose_name='Time inserted')),
                ('Attempts', models.IntegerField(default=0)),
                ('Updated', models.DateTimeField(auto_now_add=True, verbose_name='Time updated')),
                ('IP_Address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address of Login')),
            ],
            options={
                'ordering': ('Id',),
            },
        ),
        migrations.CreateModel(
            name='LoginStatus',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=50, verbose_name='Status of Login')),
            ],
            options={
                'ordering': ('Id',),
            },
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50, verbose_name='Name of User')),
                ('Inserted', models.DateTimeField(auto_now_add=True, verbose_name='Time inserted')),
            ],
            options={
                'ordering': ('Id',),
            },
        ),
        migrations.CreateModel(
            name='NameType',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=50, verbose_name='Type of Name')),
            ],
            options={
                'ordering': ('Id',),
            },
        ),
        migrations.CreateModel(
            name='PasswordStatus',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=72, verbose_name='Status of Password')),
            ],
            options={
                'ordering': ('Id',),
            },
        ),
        migrations.AlterField(
            model_name='password',
            name='Password',
            field=models.CharField(default=0, max_length=60),
        ),
        migrations.AddField(
            model_name='name',
            name='Type_Id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='SES.NameType'),
        ),
        migrations.AddField(
            model_name='name',
            name='User_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SES.User', verbose_name='Login'),
        ),
        migrations.AddField(
            model_name='login',
            name='Status_Id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='SES.LoginStatus'),
        ),
        migrations.AddField(
            model_name='login',
            name='User_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SES.User', verbose_name='Login'),
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='Status_Id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='SES.EmailAddressStatus'),
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='User_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SES.User', verbose_name='Login'),
        ),
        migrations.AddField(
            model_name='password',
            name='Status_Id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='SES.PasswordStatus'),
        ),
    ]
