# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SES', '0010_auto_20171009_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Password_Id', models.CharField(default=0, max_length=60)),
                ('Authorization_Code', models.CharField(max_length=20, verbose_name='Password Reset Code')),
                ('Inserted', models.DateTimeField(auto_now_add=True, verbose_name='Time inserted')),
            ],
            options={
                'ordering': ('Id',),
            },
        ),
        migrations.CreateModel(
            name='PasswordResetStatus',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=50, verbose_name='Status of Password Reset')),
            ],
            options={
                'ordering': ('Id',),
            },
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='Status_Id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='SES.PasswordResetStatus'),
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='User_Id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SES.User'),
        ),
    ]
