# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SES', '0013_auto_20171023_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='Filename',
            new_name='HTML_Filename',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='Body_Text',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='TXT_Filename',
            field=models.FileField(blank=True, null=True, upload_to='SES/static/templates/email/', verbose_name='Filename'),
        ),
    ]
