# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 18:58
from __future__ import unicode_literals

import SES.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SES', '0014_auto_20171024_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=100, unique=True, verbose_name='Login email of user')),
                ('Username', models.CharField(max_length=50, verbose_name='User name')),
                ('Inserted', models.DateTimeField(auto_now_add=True, verbose_name='Time inserted')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('Avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('Status_Id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='SES.UserStatus')),
            ],
            options={
                'ordering': ('Id',),
            },
            managers=[
                ('objects', SES.managers.UserManager()),
            ],
        ),
        migrations.RenameModel(
            old_name='Password',
            new_name='PasswordNotUsed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Status_Id',
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='User_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='login',
            name='User_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='name',
            name='User_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='passwordnotused',
            name='User_Id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='User_Id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
