# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SES', '0023_auto_20171025_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
