# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SES', '0024_customuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordreset',
            name='Password_Id',
        ),
    ]
